---
  - name: Install prerequisites
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common', 'python3']
      update_cache: yes

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker
    apt:
      name: docker-ce
      update_cache: yes

  - name: Install docker-compose
    shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: Set execution permission to docker-compose binary
    file:
      path: /usr/local/bin/docker-compose
      mode: "0755"

  - name: Install misc packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - tmux
      - vim

  - name: Create wiki user
    user: name=wiki shell=/bin/bash groups=sudo append=yes

  - name: Add public keys
    authorized_key: user=wiki key="{{ lookup('file', '{{ item }}') }}" state=present
    loop: "{{ lookup('fileglob', 'keys/*', wantlist=True) }}"
